### PR TITLE
Attempt to add coverage through codecov

### LINKED ISSUE #27: Add code coverage to the WebUI
Add support for code coverage reports after the tests run on the CI.

### PR DESCRIPTION
**Pull request by kelsos**
Closes #27

### CODE REVIEW

**Comment by LefterisJP** [comment]
seems to work, right? I guess the error is due to no previous report being there to compare.

**Comment by kelsos** [comment]
Yes it seems to work properly, but the error is due to not having any coverage report on master previously. It has nothing to compare the coverage change too.

**Comment by LefterisJP** [comment]
@kelsos so merge?

**Comment by kelsos** [comment]
@LefterisJP Thank you :)

**Pull request merged**
